//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioPelicula.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int PeliculasID { get; set; }
        public string NombrePelicula { get; set; }
        public string GeneroPelicula { get; set; }
        public string ActorPelicula1 { get; set; }
        public string ActorPelicula2 { get; set; }
        public string ActorPelicula3 { get; set; }
        public string ActorPelicula4 { get; set; }
        public Nullable<int> AñoPelicula { get; set; }
        public string PaisPelicula { get; set; }
        public string DirectorPelicula { get; set; }
    }
}
